# Generated by Django 2.1 on 2019-06-09 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20190609_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='subject',
            field=models.CharField(default='', max_length=20, verbose_name='科目'),
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('2', 'general'), ('1', 'easy'), ('3', 'difficult')], max_length=10, verbose_name='等级'),
        ),
    ]
